class ApplicationError(BaseException): ...


class InvalidCredentialsError(ApplicationError): ...


class InvalidRefreshTokenError(ApplicationError): ...


class EmailAlreadyExistsError(ApplicationError): ...
