class InfrastructureError(BaseException): ...


class TokenExpiredError(InfrastructureError): ...


class InvalidTokenError(InfrastructureError): ...


class UserIDNotInTokenError(InfrastructureError): ...
